# Sentiment classification with LSTM
In this notebook we will use LSTMs to do sentiment classification on the [imdb dataset](http://ai.stanford.edu/~amaas/data/sentiment/). 

In [104]:
import numpy as np 
import pandas as pd 
import os
import spacy
import string
import re
import numpy as np
from spacy.symbols import ORTH
from collections import Counter

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pack_padded_sequence

## Dataset

To get the data: <br>
`wget http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz`

In [2]:
from pathlib import Path
PATH = Path("/data2/yinterian/aclImdb/")
list(PATH.iterdir())

[PosixPath('/data2/yinterian/aclImdb/README'),
 PosixPath('/data2/yinterian/aclImdb/model-gru-86.pth'),
 PosixPath('/data2/yinterian/aclImdb/model-81.pth'),
 PosixPath('/data2/yinterian/aclImdb/model-gru.pth'),
 PosixPath('/data2/yinterian/aclImdb/model-78.pth'),
 PosixPath('/data2/yinterian/aclImdb/test'),
 PosixPath('/data2/yinterian/aclImdb/model-gru-87.pth'),
 PosixPath('/data2/yinterian/aclImdb/imdbEr.txt'),
 PosixPath('/data2/yinterian/aclImdb/train'),
 PosixPath('/data2/yinterian/aclImdb/imdb.vocab')]

In [3]:
path = PATH/"train/pos/0_9.txt"
path.read_text()

'Bromwell High is a cartoon comedy. It ran at the same time as some other programs about school life, such as "Teachers". My 35 years in the teaching profession lead me to believe that Bromwell High\'s satire is much closer to reality than is "Teachers". The scramble to survive financially, the insightful students who can see right through their pathetic teachers\' pomp, the pettiness of the whole situation, all remind me of the schools I knew and their students. When I saw the episode in which a student repeatedly tried to burn down the school, I immediately recalled ......... at .......... High. A classic line: INSPECTOR: I\'m here to sack one of your teachers. STUDENT: Welcome to Bromwell High. I expect that many adults of my age think that Bromwell High is far fetched. What a pity that it isn\'t!'

## Tokenization

In [4]:
# first time run this
#!python3 -m spacy download en

In [9]:
re_br = re.compile(r'<\s*br\s*/?>', re.IGNORECASE)
def sub_br(x): return re_br.sub("\n", x.lower())

my_tok = spacy.load('en')
def spacy_tok(x): return [tok.text for tok in my_tok.tokenizer(sub_br(x))]

In [10]:
path = PATH/"train/pos/0_9.txt"
spacy_tok(path.read_text())[:10]

['bromwell', 'high', 'is', 'a', 'cartoon', 'comedy', '.', 'it', 'ran', 'at']

### Computing vocab2index

In [11]:
pos_files = list((PATH/"train"/"pos").iterdir())
neg_files = list((PATH/"train"/"neg").iterdir())
all_files = pos_files + neg_files
all_files[:5]

[PosixPath('/data2/yinterian/aclImdb/train/pos/8030_9.txt'),
 PosixPath('/data2/yinterian/aclImdb/train/pos/8819_10.txt'),
 PosixPath('/data2/yinterian/aclImdb/train/pos/6316_8.txt'),
 PosixPath('/data2/yinterian/aclImdb/train/pos/4781_8.txt'),
 PosixPath('/data2/yinterian/aclImdb/train/pos/10085_10.txt')]

In [12]:
counts = Counter()
for path in all_files:
    counts.update(spacy_tok(path.read_text()))

In [13]:
#counts

In [14]:
len(counts.keys())

87130

In [15]:
for word in list(counts):
    if counts[word] < 5:
        del counts[word]

In [16]:
len(counts.keys())

29370

In [18]:
vocab2index = {"<PAD>":0, "UNK":1}
words = ["<PAD>", "UNK"]
for word in counts:
    vocab2index[word] = len(words)
    words.append(word)

In [14]:
#vocab2index

## Dataset

In [21]:
# This function encodes sentences without padding 
def encode_sentence(path, vocab2index):
    x = spacy_tok(path.read_text().lower())
    return np.array([vocab2index.get(w, vocab2index["UNK"]) for w in x])

In [22]:
path = PATH/"train/neg/211_4.txt"
encode_sentence(path, vocab2index)

array([  929,   732,    99,  2115,    99,   231,    23,  2888,    28,
         428,   788,   119,    52,   890,   127,  1885,   264,  1489,
         987,    93,   390,  4499,    93,  4500,    75,  2203,  1047,
          75, 18225,    47,   483,   141,  1574,    23,  2994,    34,
          26, 16331,   353,   705,   881,    73,   141,   197,  2624,
        3058,    52,     3,   184,  4303,    52, 10076,    30,   117,
          12,   264,    98,    26,  1498,  1132,     2,     8,    66,
        6401,  2205,    47,   353,    58,    23,  2115,   353,  7441,
       24959,    73,   666,   751,  1362,   141,   287,     2,  1885,
         967,    47,   696,    73,    52,  1074,   801,  5503,    47,
        1966,    73,    26,    62,    71,    52,    68,  4209,     3,
       16734,    73,    42,   490, 18225,    63, 13088,  7768,    47,
           2,    66,  2606,  4048,    58,     5,    73,  5561,   167,
         536,    42,   105,     1,   615,  4459,    71,    66,   161,
         178,   141,

In [34]:
class ImdbDataset(Dataset):
    def __init__(self, PATH, train="train"):
        self.path_to_images = PATH/train
        self.pos_files = list((self.path_to_images/"pos").iterdir())
        self.neg_files = list((self.path_to_images/"neg").iterdir())
        self.files = self.pos_files + self.neg_files
        # pos 1, neg 0
        self.y = np.concatenate((np.ones(len(self.pos_files), dtype=int),
                                np.zeros(len(self.neg_files), dtype=int)), axis=0)
        
    def __len__(self):
        return len(self.y)
    
    def __getitem__(self, idx):
        path = self.files[idx]
        return encode_sentence(path, vocab2index), self.y[idx]

In [35]:
train_ds = ImdbDataset(PATH)
test_ds = ImdbDataset(PATH, "test")

In [36]:
x, y = test_ds[0]
len(x)

779

In [37]:
x, y = train_ds[0]
len(x)

103

## collate_fn function

The `collate_fn` merges a list of samples to form a mini-batch. It is an optional parameter to our data loader. 

In [47]:
data = [([4, 545, 23, 1], 0), ([34, 84], 1), ([23, 6, 774], 0)]
sentences, labels = zip(*data)
list(sentences)

[[4, 545, 23, 1], [34, 84], [23, 6, 774]]

In [76]:
def collate_fn(data):
    """Creates mini-batch tensors from the list of tuples (sentences, labels).
    
    Need custom collate_fn because merging sequences (including padding) is not 
    supported in default. Sequences are padded to the maximum length of mini-batch 
    sequences (dynamic padding).
    
    Args:
        data: list of tuple (sentence, label). 
            - list of word indices of variable length
            - label, 0 or 1
    Returns:
        packed_batch: (PackedSequence), see torch.nn.utils.rnn.pack_padded_sequence
        sencences: torch tensor of shape (batch_size, max_len).
        labels: torch tensor of shape (batch_size, 1).
        lengths: list; valid length for each padded sentence. 
    """
    # Sort a data list by sentences length (descending order).
    data.sort(key=lambda x: len(x[0]), reverse=True)
    sentences, labels = zip(*data)
    
    # stack labels
    labels = torch.Tensor(labels).unsqueeze(1)
    
    # Merge sentences
    lengths = [len(s) for s in sentences]
   
    sents = torch.zeros(len(sentences), max(lengths)).long()
    for i, s in enumerate(sentences):
        end = lengths[i]
        sents[i, :end] = torch.Tensor(s[:end])        
    
    return sents, labels, lengths

In [77]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size=batch_size, shuffle=True, collate_fn=collate_fn)
test_dl = DataLoader(test_ds, batch_size=batch_size, collate_fn=collate_fn)

In [78]:
sents, labels, lengths = next(iter(train_dl))

In [85]:
sents.shape, labels.shape

(torch.Size([5, 606]), torch.Size([5, 1]))

In [83]:
lengths

[606, 209, 181, 169, 152]

## Understanding LSTMs 

In [21]:
# Input dim is the dimension of the embedding for each word (2 in the example)
# Output dim is the dimension of the hidden layer (4 in this example)
lstm = nn.LSTM(2, 4)  

In [22]:
inputs = [torch.randn(1, 2) for _ in range(5)] # make a sequence of length 5
inputs = torch.cat(inputs).view(len(inputs), 1, -1)
inputs

tensor([[[ 0.7282,  0.6077]],

        [[-0.3187, -0.7117]],

        [[-1.5429,  0.0020]],

        [[ 0.0564,  0.0937]],

        [[ 1.0420,  1.4207]]])

In [23]:
# RNNs assume this input shape
# input shape should be seq_len x bash_size x embedding dimension
inputs.shape

torch.Size([5, 1, 2])

In [24]:
# LSTMs need two hidden vectors instead of one
hidden = (torch.zeros(1, 1, 4), torch.zeros(1, 1, 4))

In [25]:
out, hidden = lstm(inputs, hidden)

In [26]:
print(out.shape)
out

torch.Size([5, 1, 4])


tensor([[[ 0.0284, -0.0016,  0.1897,  0.0487]],

        [[-0.0148, -0.0602,  0.1194,  0.1238]],

        [[ 0.0118,  0.0869,  0.1618,  0.1522]],

        [[-0.0112,  0.0267,  0.2195,  0.1340]],

        [[ 0.0082,  0.0329,  0.4125,  0.0744]]])

In [27]:
hidden

(tensor([[[ 0.0082,  0.0329,  0.4125,  0.0744]]]),
 tensor([[[ 0.0166,  0.1283,  0.7120,  0.3235]]]))

### Debugging our model

In [87]:
batch_size = 7
train_dl = DataLoader(train_ds, batch_size=batch_size, shuffle=True, collate_fn=collate_fn)

In [88]:
x,y,lengths = next(iter(train_dl))

In [89]:
x.shape

torch.Size([7, 320])

In [90]:
vocab_size = len(words)
embedding_dim = 10
embed = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)

In [91]:
x = embed(x.long())
x.shape

torch.Size([7, 320, 10])

In [92]:
## x should have dimensions seq_len, batch_size, embedding dimension
x = x.transpose(0,1)
x.shape

torch.Size([320, 7, 10])

In [93]:
hidden_dim = 9
lstm = nn.LSTM(embedding_dim, hidden_dim)

In [94]:
h = (torch.zeros(1, batch_size, hidden_dim),
     torch.zeros(1, batch_size, hidden_dim))

In [95]:
out, hidden = lstm(x, h)

In [96]:
out.shape

torch.Size([320, 7, 9])

In [97]:
h1, h2 = hidden
h1.shape

torch.Size([1, 7, 9])

## Model

In [153]:
class LSTMModel(torch.nn.Module) :
    def __init__(self, vocab_size, embedding_dim, hidden_dim) :
        super(LSTMModel,self).__init__()
        self.hidden_dim = hidden_dim
        self.embeddings = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
        # The LSTM takes word embeddings as inputs, and outputs hidden states
        # with dimensionality hidden_dim.
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, batch_first=True)
        self.linearOut = nn.Linear(hidden_dim, 1)
        
    def forward(self, inputs, lengths):
        x = self.embeddings(inputs)
        pack = pack_padded_sequence(x, lengths, batch_first=True)
        lstm_out, (ht, ct) = self.lstm(pack)
        x = ht[-1]
        x = self.linearOut(x)
        return x

In [161]:
def train_epocs(model, epochs=10, lr=0.001):
    parameters = filter(lambda p: p.requires_grad, model.parameters())
    optimizer = torch.optim.Adam(parameters, lr=lr)
    for i in range(epochs):
        model.train()
        sum_loss = 0.0
        total = 0
        for x, y, lengths in train_dl:
            x = x.long().cuda()
            y = y.float().cuda()
            y_pred = model(x, lengths)
            optimizer.zero_grad()
            loss = F.binary_cross_entropy_with_logits(y_pred, y)
            loss.backward()
            optimizer.step()
            sum_loss += loss.item()*y.shape[0]
            total += y.shape[0]
        print("train loss %.3f" % (sum_loss/total))
        test_metrics(model)
    return model

In [162]:
def test_metrics(model):
    model.eval()
    correct = 0
    total = 0
    sum_loss = 0.0
    for x, y, lengths in test_dl:
        x = x.long().cuda()
        y = y.float().cuda()
        y_hat = model(x, lengths)
        loss = F.binary_cross_entropy_with_logits(y_hat, y)
        y_pred = y_hat > 0
        correct += (y_pred.float() == y).float().sum()
        total += y.shape[0]
        sum_loss += loss.item()*y.shape[0]
    print("test loss %.3f and accuracy %.3f" % (sum_loss/total, correct/total))

In [163]:
train_ds = ImdbDataset(PATH, "train")
test_ds = ImdbDataset(PATH, "test")

In [164]:
batch_size = 500
train_dl = DataLoader(train_ds, batch_size=batch_size, shuffle=True, collate_fn=collate_fn)
test_dl = DataLoader(test_ds, batch_size=batch_size, collate_fn=collate_fn)

In [165]:
vocab_size = len(words)
print(vocab_size)
model = LSTMModel(vocab_size, 50, 100).cuda()

29372


In [166]:
model = train_epocs(model, epochs=5, lr=0.01)

train loss 0.651
test loss 0.558 and accuracy 0.718
train loss 0.548
test loss 0.529 and accuracy 0.749
train loss 0.392
test loss 0.396 and accuracy 0.831
train loss 0.275
test loss 0.505 and accuracy 0.768
train loss 0.255
test loss 0.397 and accuracy 0.857


In [184]:
def save_model(m, p): torch.save(m.state_dict(), p)
    
def load_model(m, p): m.load_state_dict(torch.load(p))

In [51]:
p = PATH/"model-81.pth"
save_model(model, p)

In [52]:
test_metrics(model)

test loss 0.939 and accuracy 0.817


In [49]:
load_model(model, p)

## GRU model with dropout

In [186]:
class GRUModel(torch.nn.Module) :
    def __init__(self, vocab_size, embedding_dim, hidden_dim):
        super(GRUModel, self).__init__()
        self.hidden_dim = hidden_dim
        self.embeddings = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
        # The LSTM takes word embeddings as inputs, and outputs hidden states
        # with dimensionality hidden_dim.
        self.dropout = nn.Dropout(0.5)
        self.gru = nn.GRU(embedding_dim, hidden_dim, batch_first=True)
        self.linearOut = nn.Linear(hidden_dim, 1)
        
    def forward(self, inputs, lengths):
        x = self.embeddings(inputs)
        pack = pack_padded_sequence(x, lengths, batch_first=True)
        out, ht = self.gru(pack)
        x = ht[-1]
        x = self.dropout(x)
        x = self.linearOut(x)
        return x

In [187]:
vocab_size = len(words)
print(vocab_size)
model2 = GRUModel(vocab_size, 50, 50).cuda()

29372


In [188]:
model2 = train_epocs(model2, epochs=5, lr=0.01)

train loss 0.648
test loss 0.623 and accuracy 0.663
train loss 0.512
test loss 0.377 and accuracy 0.841
train loss 0.261
test loss 0.270 and accuracy 0.889
train loss 0.144
test loss 0.306 and accuracy 0.887
train loss 0.074
test loss 0.377 and accuracy 0.882


In [189]:
p = PATH/"model-gru-88.pth"
save_model(model2, p)

## Exercise:
Start with pre-trained embeddings.

## References

The model in this notebook is adapted from this [pytorch tutorial](https://pytorch.org/tutorials/beginner/nlp/sequence_models_tutorial.html). 

The data loader function `collate_fn` has been adapted from [here](https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/03-advanced/image_captioning/data_loader.py).